# Generated by Django 5.0.6 on 2024-07-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_code', models.CharField(max_length=15)),
                ('full_name', models.CharField(help_text='Complain applicant name', max_length=100)),
                ('sex', models.CharField(help_text='Complain applicant gender', max_length=10)),
                ('age', models.IntegerField(help_text='Complain Applicant age')),
                ('disability_status', models.CharField(help_text='Complain applicant disability status', max_length=7)),
                ('phone_number', models.CharField(help_text='Complain applicant mobile number', max_length=100)),
                ('organization_name', models.CharField(help_text='Organization name', max_length=200)),
                ('complain_adjenda', models.TextField(help_text='Main ideas of the complain')),
                ('additional_info', models.TextField(blank=True, help_text='Complaint additional note')),
                ('attachement', models.CharField(blank=True, help_text='Complaint additional attachment', max_length=1000)),
                ('date_complained', models.CharField(help_text='Date of Complained', max_length=20)),
                ('feedback_status', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('appeal_again', models.IntegerField()),
                ('max_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ComplainFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_finding', models.TextField()),
                ('is_complain_correct', models.CharField(max_length=20)),
                ('note_on_complain_correction', models.TextField()),
                ('complain_inacceptance', models.TextField()),
                ('complain_decision_maker', models.CharField(max_length=100)),
                ('officer_comment', models.TextField()),
                ('date_feedback', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.CharField(blank=True, max_length=100)),
                ('reported_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilesAttached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complient_id', models.CharField(max_length=15)),
                ('status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complient_id', models.CharField(max_length=15)),
                ('message', models.CharField(help_text='Complain message/comment', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, help_text='Complained Region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.region')),
                ('wereda', models.ForeignKey(blank=True, help_text='Complained Wereda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.wereda')),
                ('zone', models.ForeignKey(blank=True, help_text='Complained Zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.zone')),
            ],
        ),
    ]
