# Generated by Django 5.0.6 on 2024-07-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_initial'),
        ('complain', '0001_initial'),
        ('department', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Complain Department ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='complain',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Assigned Employee ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.employee'),
        ),
        migrations.AddField(
            model_name='complain',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Complained region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.region'),
        ),
        migrations.AddField(
            model_name='complain',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.service'),
        ),
        migrations.AddField(
            model_name='complain',
            name='wereda',
            field=models.ForeignKey(blank=True, help_text='Complained Wereda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.wereda'),
        ),
        migrations.AddField(
            model_name='complain',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Complained Zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.zone'),
        ),
        migrations.AddField(
            model_name='complainfeedback',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.complain'),
        ),
        migrations.AddField(
            model_name='complainfeedback',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.region'),
        ),
        migrations.AddField(
            model_name='complainfeedback',
            name='wereda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.wereda'),
        ),
        migrations.AddField(
            model_name='complainfeedback',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.zone'),
        ),
        migrations.AddField(
            model_name='filesattached',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.complain'),
        ),
        migrations.AddField(
            model_name='filesattached',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.region'),
        ),
        migrations.AddField(
            model_name='filesattached',
            name='wereda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.wereda'),
        ),
        migrations.AddField(
            model_name='filesattached',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.zone'),
        ),
        migrations.AddField(
            model_name='result',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Result Region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.region'),
        ),
        migrations.AddField(
            model_name='result',
            name='wereda',
            field=models.ForeignKey(blank=True, help_text='Result Wereda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.wereda'),
        ),
        migrations.AddField(
            model_name='result',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Result Zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.zone'),
        ),
    ]
