# Generated by Django 5.0.6 on 2024-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Guest Full Name', max_length=100)),
                ('sex', models.CharField(help_text='Guest Gender', max_length=5)),
                ('email', models.EmailField(blank=True, help_text='Guest Email Address (Optional)', max_length=50, null=True)),
                ('phone_number', models.CharField(help_text='Guest Phone Number', max_length=15)),
                ('org', models.CharField(help_text='Organization the guest comes from', max_length=100)),
                ('subject', models.CharField(help_text='Any suggestion by guest', max_length=100)),
                ('app_date', models.DateField(help_text='Appointment Date')),
                ('app_time', models.CharField(help_text='Appointment Time', max_length=100)),
                ('short_code', models.CharField(help_text='Appointment followup code auto generated by the system', max_length=100)),
                ('status', models.CharField(help_text='Status updated by Admin', max_length=100)),
                ('feedback', models.CharField(help_text='Feedback from Admin', max_length=300)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.CharField(help_text='Attachment', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('office_no', models.CharField(max_length=100)),
                ('floor_no', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
