from django.db import models
from .models import Zone, Wereda, Department, Employee, Service


from django.db import models
from department.models import *


class Employee(models.Model):
    employee_id = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100)
    sex = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    role = models.ForeignKey(Position, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, blank=True)
    zone = models.ForeignKey(Zone, on_delete=models.SET_NULL, null=True, blank=True)
    wereda = models.ForeignKey(Wereda, on_delete=models.SET_NULL, null=True, blank=True)
    phone_number = models.CharField(max_length=100)
    office_no = models.CharField(max_length=100)
    floor_no = models.CharField(max_length=100)
    photo = models.CharField(max_length=100)
    date_registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Appointment(models.Model):
    full_name = models.CharField(max_length=100, help_text="Guest Full Name")
    sex = models.CharField(max_length=5, help_text="Guest Gender")
    email = models.EmailField(max_length=50, null=True, blank=True, help_text="Guest Email Address (Optional)")
    phone_number = models.CharField(max_length=15, help_text="Guest Phone Number")
    zone = models.ForeignKey(Zone, on_delete=models.SET_NULL, null=True, blank=True, help_text='Complained Zone')
    wereda = models.ForeignKey(Wereda, on_delete=models.SET_NULL, null=True, blank=True, help_text='Complained Wereda')
    org = models.CharField(max_length=100, help_text="Organization the guest comes from")
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True, help_text="Service Department ID")
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True, help_text="Assigned Employee ID")
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True, help_text="Service ID")
    subject = models.CharField(max_length=100, help_text="Any suggestion by guest")
    app_date = models.DateField(help_text="Appointment Date")
    app_time = models.CharField(max_length=100, help_text="Appointment Time")
    short_code = models.CharField(max_length=100, help_text="Appointment followup code auto generated by the system")
    status = models.CharField(max_length=100, help_text="Status updated by Admin")
    feedback = models.CharField(max_length=300, help_text="Feedback from Admin")
    date_registered = models.DateTimeField(auto_now_add=True)
    attachment = models.CharField(max_length=300, help_text="Attachment")

    def __str__(self):
        return self.full_name
